#!/bin/sh

set -e

lb config noauto \
    --distribution trixie \
    --architecture amd64 \
    --binary-image iso-hybrid \
    --archive-areas "main contrib non-free-firmware" \
    --apt-recommends true \
    --security true \
    --source false \
    --debian-installer none \
    --image-name "moeha-os" \
    --iso-application "Moeha OS" \
    --iso-publisher "Moeha OS Project" \
    --iso-volume "MOEHA_OS" \
    "${@}"
